authentication/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_handler, name='logout'),
]

ecommerce/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("product/list/", views.ProductColorListView.as_view(), name="product-list"),
    path("product/<int:pk>/", views.ProductColorDetailView.as_view(), name="product"),
    path("order/create/", views.OrderCreateView.as_view(), name="order-create"),
]

web_ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("ecommerce.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    email = models.EmailField(_("email"), max_length=254, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

authentication/forms.py
from django import forms
from django.contrib.auth import authenticate, login
from .models import CustomUser


class LoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(attrs={"class": "input", "placeholder":"Email"}),
        max_length=150,
        required=True,
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "input", "placeholder":"Contraseña"}), required=True
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        user = authenticate(email=email, password=password)

        if not user:
            raise forms.ValidationError("Correo electrónico o contraseña incorrectos.")

    def login(self, request):
        email = self.cleaned_data.get("email")
        user = CustomUser.objects.get(email=email)
        login(request, user)


class SignUpForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "input", "placeholder":"Nombre"}),
        max_length=100,
        required=True,
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "input", "placeholder":"Apellido"}),
        max_length=100,
        required=True,
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={"type": "email", "class": "input", "placeholder":"Correo electrónico"}),
        required=True,
    )
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "input", "placeholder":"Contraseña"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "input", "placeholder":"Confirmar contraseña"}))

    class Meta:
        model = CustomUser

    def clean(self):
        email = self.cleaned_data.get("email")
        if CustomUser.objects.filter(email=email):
            raise forms.ValidationError("Correo electrónico ya registrado.")

        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 != password2:
            raise forms.ValidationError("Contraseñas no coinciden.")

    def signup(self, request):
        email = self.cleaned_data.get("email")
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 == password2:

            user = CustomUser.objects.create(
                email=email,
                username=email,
                first_name=first_name,
                last_name=last_name,
            )
            user.set_password(password1)
            user.save()

authentication/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView
from django.contrib.auth import logout
from .forms import SignUpForm, LoginForm


class SignUpView(View):
    template_name = "authentication/signup.html"
    form_class = SignUpForm

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("home")
        form = self.form_class
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.signup(request)
            return redirect("login")
        else:
            return render(request, self.template_name, {"form": form})


class LoginView(TemplateView):
    template_name = "authentication/login.html"
    form_class = LoginForm

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("home")
        form = self.form_class
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            form.login(request)
            try:
                return redirect(self.request.GET['next'])
            except:
                return redirect("home")
        else:
            return render(request, self.template_name, {"form": form})
        
    


def logout_handler(request):
    logout(request)
    return redirect("login")

authentication/templates/authentication/login.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}
  Iniciar Sesión
{% endblock %}

{% block content %}
  <section class="section-login">
    <div class="background-image">
      <img src="{% static 'img/background-image.jpg' %}" alt="">
    </div>
    <div class="login">
      <div class="header-form">
        <h3>INICIAR SESIÓN</h3>
      </div>
      <form action="" class="login-form" id="id_login_form" method="post">
        {% csrf_token %}
        <div class="field">
          <label for="id_email" class="label">Email</label>
          {{ form.email }}
        </div>
        <div class="field">
          <label for="id_password" class="label">Contraseña</label>
          {{ form.password }}
        </div>
        {% if form.non_field_errors %}
          <div class="errors">
            {% for error in form.non_field_errors %}
              <p class="error">{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
        <div class="login-buttons">
          <button class="button login-button">Iniciar sesión</button>
          <hr />
          <a class="button signup-button" href="{% url 'signup' %}">Registrarse</a>
        </div>
      </form>
    </div>
  </section>
{% endblock %}

authentication/templates/authentication/signup.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}
  Registrarse
{% endblock %}

{% block content %}
  <div class="signup">
    <form method="post" class="form">
      {% csrf_token %}
      <div>
        <h2>Bienvenido a todosorteos</h2>
        <h4>Prepárate para ganar increíbles premios</h4>
      </div>
      <div class="form-fields">
        <h3>Registrarse</h3>
        <label class="label" for="id_email">Email</label>
        {{ form.email }}

        <label class="label" for="id_first_name">Nombre</label>
        {{ form.first_name }}

        <label class="label" for="id_last_name">Apellido</label>
        {{ form.last_name }}

        <label class="label" for="id_password1">Contraseña</label>
        {{ form.password1 }}

        <label class="label" for="id_password2">Confirmar contraseña</label>
        {{ form.password2 }}

        <label class="label" for="id_phone_number">Nro. de teléfono</label>
        <div class="input-phone-number">
          {{ form.phone_number }}
        </div>


        <div class="errors">
          {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
              <div class="error">
                <p>{{ error }}</p>
              </div>
            {% endfor %}
          {% endif %}

          {% for field in form %}
            {% if field.errors %}
              {% for error in field.errors %}
                <div class="error">
                  <p>{{ error }}</p>
                </div>
              {% endfor %}
            {% endif %}
          {% endfor %}
        </div>

        <button class="button">Registrarse</button>
        <small>Ya tienes una cuenta?, <a href="{% url 'login' %}"><b>iniciar sesión</b></a></small>
      </div>
    </form>
    <div class="background-login">
      <img src="{% static 'img/background-login.png' %}" alt="" />
    </div>
  </div>
{% endblock %}