ecommerce/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("product/list/", views.ProductColorListView.as_view(), name="product-list"),
    path("product/<int:pk>/", views.ProductColorDetailView.as_view(), name="product"),
    path("order/create/", views.OrderCreateView.as_view(), name="order-create"),
]

web_ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("ecommerce.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator
from simple_history.models import HistoricalRecords


class Category(models.Model):
    subcategory_of = models.ForeignKey(
        "ecommerce.Category",
        verbose_name=_("Categoría"),
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    name = models.CharField(_("Nombre"), max_length=100)

    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product_color = models.ForeignKey(
        "ecommerce.ProductColor",
        verbose_name=_(""),
        on_delete=models.CASCADE,
        related_name="productimage",
    )
    image = models.ImageField(_("Imagen"), upload_to="products")

    class Meta:
        verbose_name = _("productimage")
        verbose_name_plural = _("productimages")


class Product(models.Model):
    name = models.CharField(_("Nombre"), max_length=200)
    description = models.TextField(_("Descripción"))
    category = models.ForeignKey(
        "ecommerce.Category",
        verbose_name=_("Categoría"),
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    price = models.FloatField(_("Precio"))
    history = HistoricalRecords()

    class Meta:
        verbose_name = _("product")
        verbose_name_plural = _("products")

    def __str__(self):
        return self.name


class ProductColor(models.Model):
    product = models.ForeignKey(
        "ecommerce.Product", verbose_name=_("Producto"), on_delete=models.CASCADE
    )
    color = models.CharField(_("Color"), max_length=50)
    discount = models.PositiveIntegerField(
        _("Descuento"), default=0, validators=[MaxValueValidator(100)]
    )
    history = HistoricalRecords()

    class Meta:
        verbose_name = _("Product (color)")
        verbose_name_plural = _("Products (color)")

    def __str__(self):
        return f"{self.product.name} ({self.color})"


class ProductSize(models.Model):
    product_color = models.ForeignKey(
        "ecommerce.ProductColor",
        verbose_name=_("Producto (Color)"),
        related_name="productsize",
        on_delete=models.CASCADE,
    )
    size = models.CharField(_("Talla"), max_length=50)
    stock = models.IntegerField(_("Stock"), default=0)

    class Meta:
        verbose_name = _("productsize")
        verbose_name_plural = _("productsizes")
        
    def __str__(self):
        return f'{self.product_color} ({self.size})'


class Order(models.Model):
    user = models.ForeignKey(
        "authentication.CustomUser", verbose_name=_("Usuario"), on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        "ecommerce.ProductSize", verbose_name=_("Producto"), on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField(_("Cantidad"))

    class Meta:
        verbose_name = _("order")
        verbose_name_plural = _("orders")

    def __str__(self):
        return f'{self.user.email} | {self.product} | {self.quantity}'

ecommerce/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    
    class Meta:
        model = Order
        fields = ("user", "product", "quantity")

ecommerce/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from .models import ProductColor, Order, ProductSize
from .forms import OrderForm


class HomeView(TemplateView):
    template_name = "ecommerce/home.html"


class ProductColorListView(ListView):
    model = ProductColor
    template_name = "ecommerce/_product_list.html"
    

class ProductColorDetailView(DetailView):
    model = ProductColor
    template_name = "ecommerce/_product.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["colors"] = ProductColor.objects.filter(product__pk=self.get_object().product.pk)
        return context
    

class OrderCreateView(CreateView):
    model = Order
    template_name = "ecommerce/_order_create.html"
    form_class = OrderForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["product"] = ProductSize.objects.get(pk=self.request.GET['size'])
        context["max_quantity"] = range(1, context["product"].stock + 1) if context["product"].stock < 10 else range(1, 11) 
        return context
    
    
    def post(self, request, *args, **kwargs):
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            
            return redirect("product", ProductSize.objects.get(pk=request.POST['product']).product_color.pk)
            
        return super().post(request, *args, **kwargs)

ecommerce/templates/ecommerce/_order_create.html
<form action="{% url 'order-create' %}?size={{ product.pk }}" method="post" class="form-order-create">
  {% csrf_token %}
  <input type="hidden" name="user" value="{{ user.pk }}" />
  <input type="hidden" name="product" value="{{ product.pk }}" />

  <div class="form-quantity">
    <div class="form-field">
      <label for="id_quantity">
        Cantidad:
      </label>
      <select class="select-quantity" name="quantity" id="id_quantity">
        {% for num in max_quantity %}
          <option value="{{ num }}">{{ num }}</option>
        {% endfor %}
      </select>
    </div>
    {% if product.stock < 10 and product.stock > 1 %}
      <p class="extra-quantity">¡Últimos {{ product.stock }} disponibles!</p>
    {% elif product.stock == 1 %}
      <p class="extra-quantity">¡Último disponible!</p>
    {% endif %}
  </div>
  {% if not user.is_authenticated %}
    <a class="button-add-to-cart" href="{% url 'login' %}?next={% url 'product' product.product_color.pk %}">Añadir al carrito +</a>
  {% else %}
    <button id="id_button_add_to_cart" class="button-add-to-cart">Añadir al carrito +</button>
  {% endif %}
</form>

ecommerce/templates/ecommerce/_product.html
{% extends 'core/base.html' %}

{% block content %}
  <section class="section-product">
    <div class="product">
      <div class="category">
        {% if object.product.category.subcategory_of %}
          <a href="">{{ object.product.category.subcategory_of.name }}</a>
          <svg width="16px" height="16px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
            <g id="SVGRepo_iconCarrier">
              <path d="M9.71069 18.2929C10.1012 18.6834 10.7344 18.6834 11.1249 18.2929L16.0123 13.4006C16.7927 12.6195 16.7924 11.3537 16.0117 10.5729L11.1213 5.68254C10.7308 5.29202 10.0976 5.29202 9.70708 5.68254C9.31655 6.07307 9.31655 6.70623 9.70708 7.09676L13.8927 11.2824C14.2833 11.6729 14.2833 12.3061 13.8927 12.6966L9.71069 16.8787C9.32016 17.2692 9.32016 17.9023 9.71069 18.2929Z" fill="#999999"></path>
            </g>
          </svg>
        {% endif %}
        <a href="">{{ object.product.category.name }}</a>
      </div>
      <h3 class="header-xs">{{ object.product.name }}</h3>
      <div class="product-image">
        <div class="main-product-image">
          <img src="{{ object.productimage.first.image.url }}" alt="" id="id_main_productimage" />
        </div>
        <div class="selector-product-images">
          {% for productimage in object.productimage.all %}
            <div class="selector-image" hx-on:mouseover="changeImage('{{ productimage.image.url }}')">
              <img src="{{ productimage.image.url }}" alt="" />
            </div>
          {% endfor %}
        </div>
      </div>
      <div class="product-info">
        <h2 class="header-md">{{ object.product.name }}</h2>
        <div class="price">
          <p class="product-price-total" id="id_product_total_price_{{ object.pk }}"></p>
          {% if object.discount != 0 %}
            <p class="product-price" id="id_product_price_{{ object.pk }}">{{ object.price }}</p>
            <p class="product-discount">- {{ object.discount }}%</p>
          {% endif %}
        </div>

        <p class="field-name">Color: <b>{{ object.color }}</b></p>
        <div class="selector-product-colors">
          {% for product in colors %}
            <div>
              <a href="{% url 'product' product.pk %}"><img src="{{ product.productimage.first.image.url }}" alt="" /></a>
            </div>
          {% endfor %}
        </div>

        <p class="field-name">
          Talla: <b id="id_size"></b>
        </p>
        <div class="selector-product-size">
          {% for size in object.productsize.all %}
            <button class="button-size" hx-get="{% url 'order-create' %}?size={{ size.pk }}" hx-target="#id_add_to_cart" hx-on:click="setSize({{ size.size }})">{{ size.size }}</button>
          {% endfor %}
        </div>

        <div id="id_add_to_cart" hx-get="{% url 'order-create' %}?size={{ object.productsize.first.pk }}" hx-trigger="load"></div>
      </div>
    </div>
  </section>
{% endblock %}

{% block extra_js %}
  <script>
    function setSize(size) {
      htmx.find('#id_size').innerHTML = size
    }
    
    window.onload = () => {
      showPrice(htmx.find('#id_product_total_price_{{ object.pk }}'), "{{ object.product.price|stringformat:'.2f' }}", "{{ object.discount|stringformat:'.2f' }}")
      showPrice(htmx.find('#id_product_price_{{ object.pk }}'), "{{ object.product.price|stringformat:'.2f' }}", 0)
      setSize('{{ object.productsize.first.size }}')
    }
  </script>
{% endblock %}

ecommerce/templates/ecommerce/_product_list.html
{% for object in object_list %}
  <a class="product" href="{% url 'product' object.pk %}" hx-on::after-process-node="showPrice(htmx.find('#id_product_total_price_{{ object.pk }}'), {{ object.product.price|stringformat:'.2f' }}, {{ object.discount|stringformat:'.2f' }});showPrice(htmx.find('#id_product_price_{{ object.pk }}'), {{ object.product.price|stringformat:'.2f' }}, 0);">
    <div class="product-image">
      <img src="{{ object.productimage.first.image.url }}" alt="" />
    </div>
    <div class="product-info">
      <h4 class="product-name">{{ object.product.name }}</h4>
      <p class="product-color">
        <b>Color:</b>
        {{ object.color }}
      </p>
      <div class="price">
        {% if object.discount != 0 %}
          <p class="product-price" id="id_product_price_{{ object.pk }}">{{ object.price }}</p>
          <p class="product-discount">- {{ object.discount }}%</p>
        {% endif %}
        <p class="product-price-total" id="id_product_total_price_{{ object.pk }}"></p>
      </div>
    </div>
  </a>
{% endfor %}

ecommerce/templates/ecommerce/home.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}
  Inicio
{% endblock %}

{% block content %}
  <section class="section-product-list">
    <h2>Productos disponibles</h2>
    <div id="id_product_list" class="product-list" hx-get="{% url 'product-list' %}" hx-trigger="load"></div>
  </section>
{% endblock %}